services:
  ollama:
    build:
      context: ./
      dockerfile: docker/ollama/Dockerfile
    container_name: ollama
    image: ollama
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]
    #           count: 1
  open-webui:
    build:
      context: ./
      dockerfile: docker/open-webui/Dockerfile
    container_name: ollama_ui
    image: ollama_ui
    depends_on:
      - ollama
    ports:
      - 8080:8080
    volumes:
      - ./data/open-webui:/app/backend/data
    networks:
      - ollama
    environment:
      - WEBUI_AUTH=False
      - OLLAMA_BASE_URL=http://ollama:11434

networks:
  ollama:
